// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEGnjcQk2rmNIr8M6YO6hOJA0cYSujgZs',
    appId: '1:854630072700:web:4ef9811226fe1ed78f64f9',
    messagingSenderId: '854630072700',
    projectId: 'bolaobolado-app',
    authDomain: 'bolaobolado-app.firebaseapp.com',
    storageBucket: 'bolaobolado-app.firebasestorage.app',
    measurementId: 'G-8FXB1YJZXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7QGl3ijLXdRx0ZPQtoOSyh4EEGUhLDpQ',
    appId: '1:854630072700:android:3ece062fcb6e03468f64f9',
    messagingSenderId: '854630072700',
    projectId: 'bolaobolado-app',
    storageBucket: 'bolaobolado-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGTIuRvWD5J--mjHpUEIgCEXVmMb_tFOY',
    appId: '1:854630072700:ios:b415c65b03bc705d8f64f9',
    messagingSenderId: '854630072700',
    projectId: 'bolaobolado-app',
    storageBucket: 'bolaobolado-app.firebasestorage.app',
    iosBundleId: 'com.example.bolaoBolado',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEGnjcQk2rmNIr8M6YO6hOJA0cYSujgZs',
    appId: '1:854630072700:web:a581c4070718ee5a8f64f9',
    messagingSenderId: '854630072700',
    projectId: 'bolaobolado-app',
    authDomain: 'bolaobolado-app.firebaseapp.com',
    storageBucket: 'bolaobolado-app.firebasestorage.app',
    measurementId: 'G-MXSLTG94YC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGTIuRvWD5J--mjHpUEIgCEXVmMb_tFOY',
    appId: '1:854630072700:ios:b415c65b03bc705d8f64f9',
    messagingSenderId: '854630072700',
    projectId: 'bolaobolado-app',
    storageBucket: 'bolaobolado-app.firebasestorage.app',
    iosBundleId: 'com.example.bolaoBolado',
  );

}