const List<String> phrases = [
  "Aqui a gente não ganha sozinho… só perde junto 😂",
  "Bolão: onde a esperança morre por último 🍀",
  "Se der ruim, foi estratégia. Se der bom, foi sorte 😎",
  "Mais gente apostando = mais desculpas depois",
  "Confia… dessa vez vai 🤞",
  "Aqui todo mundo é estatístico de WhatsApp 📊",
  "Apostar sozinho é triste, errar em grupo é terapia 😂",
  "Se ganhar, a gente comemora. Se perder, finge que esqueceu",
  "Aqui o palpite é forte e a fé é maior 🙏",
  "Errar junto dói menos",
  "Todo bolão começa com: “mano, imagina se ganha?”",
  "Apostando com confiança… e zero embasamento 😅",
  "Se a sorte ajudar, a gente ajuda ela também 🍀",
  "Aqui a matemática é opcional",
  "Bolão é 10% lógica e 90% esperança",
  "Apostar em grupo é dividir a culpa 🤝",
  "Confia no grupo, confia no universo ✨",
  "Aqui o palpite vem antes do bom senso",
  "Se perder, a gente tenta de novo (e de novo)",
  "Bolão feito com fé, café e zero certeza ☕",
  "Aqui todo mundo entende de número… depois do sorteio",
  "Mais palpites, mais caos 😎",
  "O famoso: agora vai!",
  "Bolão: transformando números em decepções desde sempre 😂",
  "Apostamos como se soubéssemos o que estamos fazendo",
  "Se ganhar, todo mundo era amigo desde o começo",
  "Aqui a esperança é renovável",
  "Bolão bom é aquele que gera print no grupo 📱",
  "Palpite errado, amizade certa",
  "Aqui ninguém sabe, mas todo mundo opina",
  "Apostar é fácil, acertar é detalhe",
  "Bolão nível: confia que deu",
  "A sorte tá lendo isso agora 🍀",
  "Aqui o otimismo é obrigatório",
  "Se não ganhar, pelo menos rendeu assunto",
  "Bolão é emoção até o último número 😬",
  "Erramos juntos, sonhamos juntos",
  "Aqui a gente sempre quase ganha",
  "Mais uma aposta e vai!",
  "Bolão: porque desistir não é uma opção",
  "Aqui o plano B é apostar de novo",
  "Se ganhar, foi mérito. Se perder, foi azar",
  "Apostar com os amigos é metade da diversão",
  "Aqui a esperança nunca entra em manutenção",
  "Bolão aprovado pelo grupo do WhatsApp 📲",
  "O prêmio pode não vir, mas a zoeira vem",
  "Aqui ninguém aprende com os erros",
  "Se for pra errar, que seja em grupo 😂",
];
